#!/usr/bin/env python

import sys

print "open Parser"
print "let keywords = ["

for line in sys.stdin.readlines():
    word = line.strip()
    print '    ("%s", %s);' % (word, word.upper())

print "]"
